version: '3.1'

services:
    postgres:
        image: postgres:9
        ports:
          - 5432:5432
        environment:
          - POSTGRES_PASSWORD=postgres

    zookeeper:
        image: confluentinc/cp-zookeeper:6.0.1
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

    broker:
        image: confluentinc/cp-kafka:6.0.1
        hostname: broker
        container_name: broker
        depends_on:
          - zookeeper
        ports:
          - "29092:29092"
          - "9092:9092"
          - "9101:9101"
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_JMX_PORT: 9101
          KAFKA_JMX_HOSTNAME: localhost
          
#    mongodb_container:
 #       image: mongo:latest
  #      environment:
   #         MONGO_INITDB_ROOT_USERNAME: root
    #        MONGO_INITDB_ROOT_PASSWORD: rootpassword
     #   ports:
      #    - 27017:27017
       # volumes:
        #  - mongodb_data_container:/data/db
      
#volumes:
 #   mongodb_data_container: